// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocols/bridge.proto

package com.Bridge.protocols;

public final class Bridge {
  private Bridge() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
