// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocols/bridge.proto

package com.Bridge.protocols;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string peers = 1;</code>
   * @return The peers.
   */
  java.lang.String getPeers();
  /**
   * <code>string peers = 1;</code>
   * @return The bytes for peers.
   */
  com.google.protobuf.ByteString
      getPeersBytes();
}
