// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocols/bridge.proto

package com.Bridge.protocols;

/**
 * Protobuf type {@code PeersResponse}
 */
public  final class PeersResponse extends
    com.google.protobuf.GeneratedMessageLite<
        PeersResponse, PeersResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:PeersResponse)
    PeersResponseOrBuilder {
  private PeersResponse() {
    peers_ = "";
  }
  public static final int PEERS_FIELD_NUMBER = 1;
  private java.lang.String peers_;
  /**
   * <code>string peers = 1;</code>
   * @return The peers.
   */
  @java.lang.Override
  public java.lang.String getPeers() {
    return peers_;
  }
  /**
   * <code>string peers = 1;</code>
   * @return The bytes for peers.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPeersBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(peers_);
  }
  /**
   * <code>string peers = 1;</code>
   * @param value The peers to set.
   */
  private void setPeers(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    peers_ = value;
  }
  /**
   * <code>string peers = 1;</code>
   */
  private void clearPeers() {
    
    peers_ = getDefaultInstance().getPeers();
  }
  /**
   * <code>string peers = 1;</code>
   * @param value The bytes for peers to set.
   */
  private void setPeersBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    peers_ = value.toStringUtf8();
    
  }

  public static com.Bridge.protocols.PeersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.Bridge.protocols.PeersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.Bridge.protocols.PeersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.Bridge.protocols.PeersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.Bridge.protocols.PeersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.Bridge.protocols.PeersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.Bridge.protocols.PeersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.Bridge.protocols.PeersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.Bridge.protocols.PeersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.Bridge.protocols.PeersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.Bridge.protocols.PeersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.Bridge.protocols.PeersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.Bridge.protocols.PeersResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code PeersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.Bridge.protocols.PeersResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:PeersResponse)
      com.Bridge.protocols.PeersResponseOrBuilder {
    // Construct using com.Bridge.protocols.PeersResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string peers = 1;</code>
     * @return The peers.
     */
    @java.lang.Override
    public java.lang.String getPeers() {
      return instance.getPeers();
    }
    /**
     * <code>string peers = 1;</code>
     * @return The bytes for peers.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPeersBytes() {
      return instance.getPeersBytes();
    }
    /**
     * <code>string peers = 1;</code>
     * @param value The peers to set.
     * @return This builder for chaining.
     */
    public Builder setPeers(
        java.lang.String value) {
      copyOnWrite();
      instance.setPeers(value);
      return this;
    }
    /**
     * <code>string peers = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPeers() {
      copyOnWrite();
      instance.clearPeers();
      return this;
    }
    /**
     * <code>string peers = 1;</code>
     * @param value The bytes for peers to set.
     * @return This builder for chaining.
     */
    public Builder setPeersBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPeersBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PeersResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.Bridge.protocols.PeersResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "peers_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.Bridge.protocols.PeersResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.Bridge.protocols.PeersResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.Bridge.protocols.PeersResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:PeersResponse)
  private static final com.Bridge.protocols.PeersResponse DEFAULT_INSTANCE;
  static {
    PeersResponse defaultInstance = new PeersResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PeersResponse.class, defaultInstance);
  }

  public static com.Bridge.protocols.PeersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PeersResponse> PARSER;

  public static com.google.protobuf.Parser<PeersResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

