// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocols/bridge.proto

package com.Bridge.protocols;

public interface RequestDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestData)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string peer = 1;</code>
   * @return The peer.
   */
  java.lang.String getPeer();
  /**
   * <code>string peer = 1;</code>
   * @return The bytes for peer.
   */
  com.google.protobuf.ByteString
      getPeerBytes();

  /**
   * <code>string handler = 2;</code>
   * @return The handler.
   */
  java.lang.String getHandler();
  /**
   * <code>string handler = 2;</code>
   * @return The bytes for handler.
   */
  com.google.protobuf.ByteString
      getHandlerBytes();

  /**
   * <code>string user = 3;</code>
   * @return The user.
   */
  java.lang.String getUser();
  /**
   * <code>string user = 3;</code>
   * @return The bytes for user.
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>string payload = 4;</code>
   * @return The payload.
   */
  java.lang.String getPayload();
  /**
   * <code>string payload = 4;</code>
   * @return The bytes for payload.
   */
  com.google.protobuf.ByteString
      getPayloadBytes();
}
