// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocols/bridge.proto

package com.Bridge.protocols;

/**
 * Protobuf type {@code RequestData}
 */
public  final class RequestData extends
    com.google.protobuf.GeneratedMessageLite<
        RequestData, RequestData.Builder> implements
    // @@protoc_insertion_point(message_implements:RequestData)
    RequestDataOrBuilder {
  private RequestData() {
    peer_ = "";
    handler_ = "";
    user_ = "";
    payload_ = "";
  }
  public static final int PEER_FIELD_NUMBER = 1;
  private java.lang.String peer_;
  /**
   * <code>string peer = 1;</code>
   * @return The peer.
   */
  @java.lang.Override
  public java.lang.String getPeer() {
    return peer_;
  }
  /**
   * <code>string peer = 1;</code>
   * @return The bytes for peer.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPeerBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(peer_);
  }
  /**
   * <code>string peer = 1;</code>
   * @param value The peer to set.
   */
  private void setPeer(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    peer_ = value;
  }
  /**
   * <code>string peer = 1;</code>
   */
  private void clearPeer() {
    
    peer_ = getDefaultInstance().getPeer();
  }
  /**
   * <code>string peer = 1;</code>
   * @param value The bytes for peer to set.
   */
  private void setPeerBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    peer_ = value.toStringUtf8();
    
  }

  public static final int HANDLER_FIELD_NUMBER = 2;
  private java.lang.String handler_;
  /**
   * <code>string handler = 2;</code>
   * @return The handler.
   */
  @java.lang.Override
  public java.lang.String getHandler() {
    return handler_;
  }
  /**
   * <code>string handler = 2;</code>
   * @return The bytes for handler.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHandlerBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(handler_);
  }
  /**
   * <code>string handler = 2;</code>
   * @param value The handler to set.
   */
  private void setHandler(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    handler_ = value;
  }
  /**
   * <code>string handler = 2;</code>
   */
  private void clearHandler() {
    
    handler_ = getDefaultInstance().getHandler();
  }
  /**
   * <code>string handler = 2;</code>
   * @param value The bytes for handler to set.
   */
  private void setHandlerBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    handler_ = value.toStringUtf8();
    
  }

  public static final int USER_FIELD_NUMBER = 3;
  private java.lang.String user_;
  /**
   * <code>string user = 3;</code>
   * @return The user.
   */
  @java.lang.Override
  public java.lang.String getUser() {
    return user_;
  }
  /**
   * <code>string user = 3;</code>
   * @return The bytes for user.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(user_);
  }
  /**
   * <code>string user = 3;</code>
   * @param value The user to set.
   */
  private void setUser(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    user_ = value;
  }
  /**
   * <code>string user = 3;</code>
   */
  private void clearUser() {
    
    user_ = getDefaultInstance().getUser();
  }
  /**
   * <code>string user = 3;</code>
   * @param value The bytes for user to set.
   */
  private void setUserBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    user_ = value.toStringUtf8();
    
  }

  public static final int PAYLOAD_FIELD_NUMBER = 4;
  private java.lang.String payload_;
  /**
   * <code>string payload = 4;</code>
   * @return The payload.
   */
  @java.lang.Override
  public java.lang.String getPayload() {
    return payload_;
  }
  /**
   * <code>string payload = 4;</code>
   * @return The bytes for payload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPayloadBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(payload_);
  }
  /**
   * <code>string payload = 4;</code>
   * @param value The payload to set.
   */
  private void setPayload(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    payload_ = value;
  }
  /**
   * <code>string payload = 4;</code>
   */
  private void clearPayload() {
    
    payload_ = getDefaultInstance().getPayload();
  }
  /**
   * <code>string payload = 4;</code>
   * @param value The bytes for payload to set.
   */
  private void setPayloadBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    payload_ = value.toStringUtf8();
    
  }

  public static com.Bridge.protocols.RequestData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.Bridge.protocols.RequestData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.Bridge.protocols.RequestData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.Bridge.protocols.RequestData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.Bridge.protocols.RequestData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.Bridge.protocols.RequestData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.Bridge.protocols.RequestData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.Bridge.protocols.RequestData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.Bridge.protocols.RequestData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.Bridge.protocols.RequestData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.Bridge.protocols.RequestData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.Bridge.protocols.RequestData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.Bridge.protocols.RequestData prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code RequestData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.Bridge.protocols.RequestData, Builder> implements
      // @@protoc_insertion_point(builder_implements:RequestData)
      com.Bridge.protocols.RequestDataOrBuilder {
    // Construct using com.Bridge.protocols.RequestData.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string peer = 1;</code>
     * @return The peer.
     */
    @java.lang.Override
    public java.lang.String getPeer() {
      return instance.getPeer();
    }
    /**
     * <code>string peer = 1;</code>
     * @return The bytes for peer.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPeerBytes() {
      return instance.getPeerBytes();
    }
    /**
     * <code>string peer = 1;</code>
     * @param value The peer to set.
     * @return This builder for chaining.
     */
    public Builder setPeer(
        java.lang.String value) {
      copyOnWrite();
      instance.setPeer(value);
      return this;
    }
    /**
     * <code>string peer = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPeer() {
      copyOnWrite();
      instance.clearPeer();
      return this;
    }
    /**
     * <code>string peer = 1;</code>
     * @param value The bytes for peer to set.
     * @return This builder for chaining.
     */
    public Builder setPeerBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPeerBytes(value);
      return this;
    }

    /**
     * <code>string handler = 2;</code>
     * @return The handler.
     */
    @java.lang.Override
    public java.lang.String getHandler() {
      return instance.getHandler();
    }
    /**
     * <code>string handler = 2;</code>
     * @return The bytes for handler.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHandlerBytes() {
      return instance.getHandlerBytes();
    }
    /**
     * <code>string handler = 2;</code>
     * @param value The handler to set.
     * @return This builder for chaining.
     */
    public Builder setHandler(
        java.lang.String value) {
      copyOnWrite();
      instance.setHandler(value);
      return this;
    }
    /**
     * <code>string handler = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHandler() {
      copyOnWrite();
      instance.clearHandler();
      return this;
    }
    /**
     * <code>string handler = 2;</code>
     * @param value The bytes for handler to set.
     * @return This builder for chaining.
     */
    public Builder setHandlerBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setHandlerBytes(value);
      return this;
    }

    /**
     * <code>string user = 3;</code>
     * @return The user.
     */
    @java.lang.Override
    public java.lang.String getUser() {
      return instance.getUser();
    }
    /**
     * <code>string user = 3;</code>
     * @return The bytes for user.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserBytes() {
      return instance.getUserBytes();
    }
    /**
     * <code>string user = 3;</code>
     * @param value The user to set.
     * @return This builder for chaining.
     */
    public Builder setUser(
        java.lang.String value) {
      copyOnWrite();
      instance.setUser(value);
      return this;
    }
    /**
     * <code>string user = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUser() {
      copyOnWrite();
      instance.clearUser();
      return this;
    }
    /**
     * <code>string user = 3;</code>
     * @param value The bytes for user to set.
     * @return This builder for chaining.
     */
    public Builder setUserBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserBytes(value);
      return this;
    }

    /**
     * <code>string payload = 4;</code>
     * @return The payload.
     */
    @java.lang.Override
    public java.lang.String getPayload() {
      return instance.getPayload();
    }
    /**
     * <code>string payload = 4;</code>
     * @return The bytes for payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPayloadBytes() {
      return instance.getPayloadBytes();
    }
    /**
     * <code>string payload = 4;</code>
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(
        java.lang.String value) {
      copyOnWrite();
      instance.setPayload(value);
      return this;
    }
    /**
     * <code>string payload = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      copyOnWrite();
      instance.clearPayload();
      return this;
    }
    /**
     * <code>string payload = 4;</code>
     * @param value The bytes for payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPayloadBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:RequestData)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.Bridge.protocols.RequestData();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "peer_",
            "handler_",
            "user_",
            "payload_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.Bridge.protocols.RequestData> parser = PARSER;
        if (parser == null) {
          synchronized (com.Bridge.protocols.RequestData.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.Bridge.protocols.RequestData>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:RequestData)
  private static final com.Bridge.protocols.RequestData DEFAULT_INSTANCE;
  static {
    RequestData defaultInstance = new RequestData();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RequestData.class, defaultInstance);
  }

  public static com.Bridge.protocols.RequestData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RequestData> PARSER;

  public static com.google.protobuf.Parser<RequestData> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

