// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocols/bridge.proto

package com.Bridge.protocols;

public interface ResponseDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseData)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string payload = 1;</code>
   * @return The payload.
   */
  java.lang.String getPayload();
  /**
   * <code>string payload = 1;</code>
   * @return The bytes for payload.
   */
  com.google.protobuf.ByteString
      getPayloadBytes();

  /**
   * <code>int64 status = 2;</code>
   * @return The status.
   */
  long getStatus();
}
