// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocols/bridge.proto

package com.Bridge.protocols;

/**
 * Protobuf type {@code ResponseData}
 */
public  final class ResponseData extends
    com.google.protobuf.GeneratedMessageLite<
        ResponseData, ResponseData.Builder> implements
    // @@protoc_insertion_point(message_implements:ResponseData)
    ResponseDataOrBuilder {
  private ResponseData() {
    payload_ = "";
  }
  public static final int PAYLOAD_FIELD_NUMBER = 1;
  private java.lang.String payload_;
  /**
   * <code>string payload = 1;</code>
   * @return The payload.
   */
  @java.lang.Override
  public java.lang.String getPayload() {
    return payload_;
  }
  /**
   * <code>string payload = 1;</code>
   * @return The bytes for payload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPayloadBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(payload_);
  }
  /**
   * <code>string payload = 1;</code>
   * @param value The payload to set.
   */
  private void setPayload(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    payload_ = value;
  }
  /**
   * <code>string payload = 1;</code>
   */
  private void clearPayload() {
    
    payload_ = getDefaultInstance().getPayload();
  }
  /**
   * <code>string payload = 1;</code>
   * @param value The bytes for payload to set.
   */
  private void setPayloadBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    payload_ = value.toStringUtf8();
    
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private long status_;
  /**
   * <code>int64 status = 2;</code>
   * @return The status.
   */
  @java.lang.Override
  public long getStatus() {
    return status_;
  }
  /**
   * <code>int64 status = 2;</code>
   * @param value The status to set.
   */
  private void setStatus(long value) {
    
    status_ = value;
  }
  /**
   * <code>int64 status = 2;</code>
   */
  private void clearStatus() {
    
    status_ = 0L;
  }

  public static com.Bridge.protocols.ResponseData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.Bridge.protocols.ResponseData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.Bridge.protocols.ResponseData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.Bridge.protocols.ResponseData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.Bridge.protocols.ResponseData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.Bridge.protocols.ResponseData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.Bridge.protocols.ResponseData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.Bridge.protocols.ResponseData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.Bridge.protocols.ResponseData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.Bridge.protocols.ResponseData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.Bridge.protocols.ResponseData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.Bridge.protocols.ResponseData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.Bridge.protocols.ResponseData prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ResponseData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.Bridge.protocols.ResponseData, Builder> implements
      // @@protoc_insertion_point(builder_implements:ResponseData)
      com.Bridge.protocols.ResponseDataOrBuilder {
    // Construct using com.Bridge.protocols.ResponseData.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string payload = 1;</code>
     * @return The payload.
     */
    @java.lang.Override
    public java.lang.String getPayload() {
      return instance.getPayload();
    }
    /**
     * <code>string payload = 1;</code>
     * @return The bytes for payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPayloadBytes() {
      return instance.getPayloadBytes();
    }
    /**
     * <code>string payload = 1;</code>
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(
        java.lang.String value) {
      copyOnWrite();
      instance.setPayload(value);
      return this;
    }
    /**
     * <code>string payload = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      copyOnWrite();
      instance.clearPayload();
      return this;
    }
    /**
     * <code>string payload = 1;</code>
     * @param value The bytes for payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPayloadBytes(value);
      return this;
    }

    /**
     * <code>int64 status = 2;</code>
     * @return The status.
     */
    @java.lang.Override
    public long getStatus() {
      return instance.getStatus();
    }
    /**
     * <code>int64 status = 2;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(long value) {
      copyOnWrite();
      instance.setStatus(value);
      return this;
    }
    /**
     * <code>int64 status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      copyOnWrite();
      instance.clearStatus();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ResponseData)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.Bridge.protocols.ResponseData();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "payload_",
            "status_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0002" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.Bridge.protocols.ResponseData> parser = PARSER;
        if (parser == null) {
          synchronized (com.Bridge.protocols.ResponseData.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.Bridge.protocols.ResponseData>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ResponseData)
  private static final com.Bridge.protocols.ResponseData DEFAULT_INSTANCE;
  static {
    ResponseData defaultInstance = new ResponseData();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ResponseData.class, defaultInstance);
  }

  public static com.Bridge.protocols.ResponseData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ResponseData> PARSER;

  public static com.google.protobuf.Parser<ResponseData> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

